[project]
name = "heic-to-jpeg-converter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=11.2.1",
    "pillow-heif>=0.22.0",
]
